# NOME DA APLICACAO
spring.application.name=rental-cars-spring-api

## API REST
spring.mvc.servlet.path=/api

## AUTENTICACAO E AUTORIZACAO
## Cors
cors.allowed-origins-front=http://localhost:4200


## BANCO DE DADOS

# Atributos da conexao
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Configuracao do Liquibase
spring.liquibase.change-log=classpath:liquibase/changelog.xml

# ? CONFIGURAÇÕES MULTIPART COMPLETAS
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.file-size-threshold=1KB
#spring.servlet.multipart.location=${java.io.tmpdir}
spring.servlet.multipart.resolve-lazily=false

server.tomcat.max-http-form-post-size=10MB
server.tomcat.max-swallow-size=10MB

# Configuracao de Swagger para suportar uploads
springdoc.show-actuator=true

# ? LOGS PARA DEBUG (opcional)
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web.cors=DEBUG